In [1]:
import pandas as pd
import numpy as np
from scipy import signal
import pywt
from scipy.stats import entropy
import matplotlib.pyplot as plt
import math
import neurokit2 as nk


df = pd.read_csv('/home/cmn/BCI/Data/Data/20200605_2030.csv')
df

,Time:125Hz,Epoch,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,...,Channel 13,Channel 14,Channel 15,Channel 16,Channel 17,Channel 18,Channel 19,Event Id,Event Date,Event Duration
0,0.000000,0,12767.807617,11262.596680,-47072.460938,-99809.117188,-18629.507812,11496.596680,14866.748047,-18494.101562,...,-33343.460938,26669.429688,-483.803497,54378.261719,-0.040,0.138,-0.952,NaN,NaN,NaN
1,0.008000,0,3146.007812,1642.808472,-47604.410156,-100928.562500,-19923.181641,8986.697266,9700.298828,-19774.095703,...,-31874.703125,29656.472656,2344.854492,58556.875000,-0.040,0.138,-0.952,NaN,NaN,NaN
2,0.016000,0,9114.437500,7613.540527,-47917.847656,-100838.617188,-20834.865234,7522.926270,10219.417969,-20394.892578,...,-34173.355469,25692.123047,-2777.114746,53062.925781,-0.036,0.136,-0.958,NaN,NaN,NaN
3,0.024000,0,9053.618164,7544.920410,-46760.406250,-99826.171875,-18187.792969,12200.721680,14403.016602,-18263.318359,...,-31805.726562,29216.277344,2670.184082,57853.890625,-0.036,0.136,-0.958,NaN,NaN,NaN
4,0.032000,0,3012.076172,1502.171265,-48211.617188,-101453.242188,-21726.923828,5733.959961,6786.101074,-21249.667969,...,-33017.707031,27959.416016,-772.722107,56272.773438,-0.036,0.136,-0.958,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345883,2767.063998,10808,60511.644531,53048.601562,71828.851562,31068.542969,187500.000000,187500.000000,81168.593750,1855.708862,...,51867.824219,187500.000000,43257.417969,187500.000000,0.002,0.030,-0.962,NaN,NaN,NaN
345884,2767.071998,10808,78874.992188,71398.398438,79472.273438,31307.998047,187500.000000,187500.000000,84630.585938,-210.352264,...,45051.949219,187500.000000,49893.539062,187500.000000,0.002,0.030,-0.962,NaN,NaN,NaN
345885,2767.079998,10808,74742.085938,67277.968750,85200.507812,34453.671875,187500.000000,187500.000000,88920.218750,5366.586426,...,51780.875000,187500.000000,41428.285156,187500.000000,0.002,0.030,-0.962,NaN,NaN,NaN
345886,2767.087998,10808,64163.675781,56679.730469,69398.093750,28923.402344,187500.000000,187500.000000,77880.757812,-922.724670,...,47757.070312,187500.000000,50945.925781,187500.000000,0.002,0.030,-0.962,NaN,NaN,NaN
345887,2767.095998,10808,86511.687500,79029.843750,90274.710938,34440.503906,187500.000000,187500.000000,90947.390625,4541.472168,...,47565.917969,187500.000000,46276.558594,187500.000000,0.002,0.030,-0.962,NaN,NaN,NaN

In [2]:
#convert data into arrays
dataset = df.values
dataset
l = len(dataset)
print(l)
print(dataset[:37502,5])

345888
[ -99809.1171875 -100928.5625    -100838.6171875 ...  -67650.125
  -71147.0546875  -66230.875    ]

In [3]:
ch4 = dataset[:,5]
time = dataset[:,1]

In [4]:
awake = dataset[:37502,1]

tired = dataset[308386:345889,1]

In [5]:
d1 = dataset[0:10000,5]
d2 = dataset[10000:20000,5]
d3 = dataset[20000:30000,5]
d4 = dataset[30000:40000,5]
d5 = dataset[40000:50000,5]
d6 = dataset[50000:60000,5]
d7 = dataset[60000:70000,5]
d8 = dataset[70000:80000,5]
d9 = dataset[80000:90000,5]
d10 = dataset[90000:100000,5]
d11 = dataset[100000:110000,5]
d12 = dataset[110000:120000,5]
d13 = dataset[120000:130000,5]
d14 = dataset[130000:140000,5]
d15 = dataset[140000:150000,5]
d16 = dataset[150000:160000,5]
d17 = dataset[160000:170000,5]
d18 = dataset[170000:180000,5]
d19 = dataset[180000:190000,5]
d20 = dataset[200000:210000,5]
d21 = dataset[210000:220000,5]
d22 = dataset[220000:230000,5]
d23 = dataset[230000:240000,5]
d24 = dataset[240000:250000,5]
d13 = dataset[250000:260000,5]
d14 = dataset[260000:270000,5]
d15 = dataset[270000:280000,5]
d16 = dataset[280000:290000,5]
d17 = dataset[290000:300000,5]
d18 = dataset[310000:320000,5]
d19 = dataset[330000:340000,5]
d20 = dataset[340000:350000,5]

In [6]:
sample_d1 = nk.entropy_sample(d1)
print(sample_d1)
sample_d2 = nk.entropy_sample(d2)
print(sample_d2)
sample_d3 = nk.entropy_sample(d3)
print(sample_d3)
sample_d4 = nk.entropy_sample(d4)
print(sample_d4)
sample_d5 = nk.entropy_sample(d5)
print(sample_d5)
sample_d6 = nk.entropy_sample(d6)
print(sample_d6)
sample_d7 = nk.entropy_sample(d7)
print(sample_d7)
sample_d8 = nk.entropy_sample(d8)
print(sample_d8)
sample_d9 = nk.entropy_sample(d9)
print(sample_d9)
sample_d10 = nk.entropy_sample(d10)
print(sample_d10)
sample_d11 = nk.entropy_sample(d11)
print(sample_d11)
sample_d12 = nk.entropy_sample(d12)
print(sample_d12)
sample_d13 = nk.entropy_sample(d13)
print(sample_d13)
sample_d14 = nk.entropy_sample(d14)
print(sample_d14)
sample_d15 = nk.entropy_sample(d15)
print(sample_d15)
sample_d16 = nk.entropy_sample(d16)
print(sample_d16)
sample_d17 = nk.entropy_sample(d17)
print(sample_d17)
sample_d18 = nk.entropy_sample(d18)
print(sample_d18)
sample_d19 = nk.entropy_sample(d19)
print(sample_d19)
sample_d20 = nk.entropy_sample(d20)
print(sample_d20)
print('1')
approximate_d1 = nk.entropy_approximate(d1)
print(approximate_d1)
approximate_d2 = nk.entropy_approximate(d2)
print(approximate_d2)
approximate_d3 = nk.entropy_approximate(d3)
print(approximate_d3)
approximate_d4 = nk.entropy_approximate(d4)
print(approximate_d4)
approximate_d5 = nk.entropy_approximate(d5)
print(approximate_d5)
approximate_d6 = nk.entropy_approximate(d6)
print(approximate_d6)
approximate_d7 = nk.entropy_approximate(d7)
print(approximate_d7)
approximate_d8 = nk.entropy_approximate(d8)
print(approximate_d8)
approximate_d9 = nk.entropy_approximate(d9)
print(approximate_d9)
approximate_d10 = nk.entropy_approximate(d10)
print(approximate_d10)
approximate_d11 = nk.entropy_approximate(d11)
print(approximate_d11)
approximate_d12 = nk.entropy_approximate(d12)
print(approximate_d12)
approximate_d13 = nk.entropy_approximate(d13)
print(approximate_d13)
approximate_d14 = nk.entropy_approximate(d14)
print(approximate_d14)
approximate_d15 = nk.entropy_approximate(d15)
print(approximate_d15)
approximate_d16 = nk.entropy_approximate(d16)
print(approximate_d16)
approximate_d17 = nk.entropy_approximate(d17)
print(approximate_d17)
approximate_d18 = nk.entropy_approximate(d18)
print(approximate_d18)
approximate_d19 = nk.entropy_approximate(d19)
print(approximate_d19)
approximate_d20 = nk.entropy_approximate(d20)
print(approximate_d20)

0.393215446540137
0.7386430687572423
0.6986357138078282
0.6801865427469588
0.8462912447585276
0.8799325772092572
0.8419274649897179
0.9134973599589555
0.8494607694946362
0.8160651861938977
0.5145575347015763
0.7014642595019207
0.35103522200017256
0.6002460950015087
0.030173880849875854
0.14872241160575206
0.4537328258887182
0.05295486264467821
0.5682784356698675
0.04682116827406084
1
0.46242301514574047
0.7950574360165215
0.723178834142709
0.6957771023249539
0.8073863823475644
0.794143837223416
0.8026628939953326
0.8610469048112792
0.829968622444146
0.781094822683591
0.5597461640063415
0.7178043975765656
0.36625656495649794
0.6190798303918004
0.06209701930305034
0.1492401012757001
0.49032062476201066
0.10530766331437325
0.5734575547184204
0.06605552881043186

In [7]:
entropy_sample = [0.393215446540137
,0.7386430687572423
,0.6986357138078282
,0.6801865427469588
,0.8462912447585276
,0.8799325772092572
,0.8419274649897179
,0.9134973599589555
,0.8494607694946362
,0.8160651861938977
,0.5145575347015763
,0.7014642595019207
,0.35103522200017256
,0.6002460950015087
,0.030173880849875854
,0.14872241160575206
,0.4537328258887182
,0.05295486264467821
,0.5682784356698675
,0.04682116827406084]
entropy_approximate = [0.46242301514574047
,0.7950574360165215
,0.723178834142709
,0.6957771023249539
,0.8073863823475644
,0.794143837223416
,0.8026628939953326
,0.8610469048112792
,0.829968622444146
,0.781094822683591
,0.5597461640063415
,0.7178043975765656
,0.36625656495649794
,0.6190798303918004
,0.06209701930305034
,0.1492401012757001
,0.49032062476201066
,0.10530766331437325
,0.5734575547184204
,0.06605552881043186]

In [8]:
awake = dataset[:37502,5] #first 5 mins of data
tired = dataset[308386:345889,5]

In [9]:
data = np.concatenate((awake,tired,d1,d2,d3,d4,d5,d6,d7,d8))
print(data)

[ -99809.1171875  -100928.5625     -100838.6171875  ...  -40236.58203125
  -37189.32421875  -37409.75390625]

In [10]:
labels = [1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0,0,1,0]
print(len(labels))

20

In [11]:
import pandas as pd
data = pd.DataFrame({
    'sample':entropy_sample,
    'approximate':entropy_approximate
})
data.head()

     sample  approximate
0  0.393215     0.462423
1  0.738643     0.795057
2  0.698636     0.723179
3  0.680187     0.695777
4  0.846291     0.807386

In [12]:
import numpy as np
#feature = np.reshape(feature, (2, 5))
#labels = np.reshape(labels, (2, 5))
#print(feature)
#print(labels)

In [13]:
print(data.sample)

<bound method NDFrame.sample of       sample  approximate
0   0.393215     0.462423
1   0.738643     0.795057
2   0.698636     0.723179
3   0.680187     0.695777
4   0.846291     0.807386
5   0.879933     0.794144
6   0.841927     0.802663
7   0.913497     0.861047
8   0.849461     0.829969
9   0.816065     0.781095
10  0.514558     0.559746
11  0.701464     0.717804
12  0.351035     0.366257
13  0.600246     0.619080
14  0.030174     0.062097
15  0.148722     0.149240
16  0.453733     0.490321
17  0.052955     0.105308
18  0.568278     0.573458
19  0.046821     0.066056>

In [14]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

X = data[['sample','approximate']]  # Features
y = labels  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

In [15]:
print(X_train)

      sample  approximate
17  0.052955     0.105308
12  0.351035     0.366257
9   0.816065     0.781095
3   0.680187     0.695777
0   0.393215     0.462423
16  0.453733     0.490321
8   0.849461     0.829969
19  0.046821     0.066056
18  0.568278     0.573458
11  0.701464     0.717804
10  0.514558     0.559746
5   0.879933     0.794144
15  0.148722     0.149240
14  0.030174     0.062097

In [16]:
print(X_test)

      sample  approximate
1   0.738643     0.795057
7   0.913497     0.861047
4   0.846291     0.807386
2   0.698636     0.723179
13  0.600246     0.619080
6   0.841927     0.802663

In [17]:

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [18]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8333333333333334

In [19]:
clf.predict([[0.15,0.7]])

array([1])